[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200  # MB

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0f766e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f9"
textColor = "#111827"
font = "sans serif"
